# language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tsedeq3/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true tsedeq3/docker-react npm run test