version: '3'
services:
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        # tty: true
        ports:
            - "3002:3000"
        volumes:
            - /app/node_modules
            - .:/app
            # - C:/Users/v63158/Documents/docker-kubernetes/frontend:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
            # - C:/Users/v63158/Documents/docker-kubernetes/frontend:/app
        command: ["npm", "run", "test"]